// Attendance figures per burn.
//
// No data feed carries attendance. `public/attendance.json` is GENERATED by
// scripts/scrape-attendance.mjs (weekly) — best-effort Wikipedia/website
// scraping merged on top of the hand-curated, authoritative
// `public/attendance-overrides.json`. Keyed by burnKey (slug minus -YYYY).
// Each record states its confidence so the UI stays honest: a reported figure
// links to its source; an estimate is labelled "Estimated"; a burn with no
// record displays "NA".

import { burnKey } from '../lib/groupByBurn';

export type AttendanceConfidence = 'reported' | 'estimated' | 'capacity';

export interface AttendanceRecord {
  /** Point estimate. null = explicitly unknown. */
  estimate: number | null;
  low?: number;
  high?: number;
  confidence: AttendanceConfidence;
  source?: string;
  sourceUrl?: string;
  year?: number;
}

const BASE = (import.meta.env.BASE_URL ?? '/').replace(/\/+$/, '/');

export async function loadAttendance(signal?: AbortSignal): Promise<Map<string, AttendanceRecord>> {
  try {
    // no-cache: revalidate so a deploy's fresh figures aren't masked by a
    // browser-cached copy of this small index file.
    const res = await fetch(`${BASE}attendance.json`, { signal, cache: 'no-cache' });
    if (!res.ok) return new Map();
    const json = (await res.json()) as { burns?: Record<string, AttendanceRecord> };
    return new Map(Object.entries(json.burns ?? {}));
  } catch {
    return new Map();
  }
}

/** Look up a festival's attendance by stripping its year suffix to the burnKey. */
export function attendanceFor(
  festivalSlug: string,
  map: Map<string, AttendanceRecord>,
): AttendanceRecord | null {
  return map.get(burnKey(festivalSlug)) ?? null;
}

/** Short display string: "72,000" / "~2,000" / "2,000–3,000" / "NA". */
export function formatAttendance(rec: AttendanceRecord | null): string {
  if (!rec || rec.estimate == null) return 'NA';
  const n = (v: number) => v.toLocaleString();
  if (rec.low != null && rec.high != null && rec.low !== rec.high) {
    return `${n(rec.low)}–${n(rec.high)}`;
  }
  return rec.confidence === 'estimated' ? `~${n(rec.estimate)}` : n(rec.estimate);
}

/** A sortable scalar for the data table — midpoint of a range, 0 for NA. */
export function attendanceValue(rec: AttendanceRecord | null): number {
  if (!rec || rec.estimate == null) return 0;
  if (rec.low != null && rec.high != null) return (rec.low + rec.high) / 2;
  return rec.estimate;
}

/** One-word confidence label for compact UI. */
export function confidenceLabel(rec: AttendanceRecord | null): string {
  if (!rec || rec.estimate == null) return 'NA';
  if (rec.confidence === 'reported') return 'Reported';
  if (rec.confidence === 'capacity') return 'Venue capacity';
  return 'Estimated';
}
